### PR TITLE
Few Changes

### PR DESCRIPTION
**Pull request by UnseenFaith**
1) Better performance using a switch case (it's also easier to read imo)
2) Changed settings to be a little bit more performant, and changed setInterval to use setTimeout
3) I saw you added the clients[last] check after, and I wasn't sure if that was intended or not, but given the context of the code, without any outside factors, if clients[last] was a falsy value then trying to set the id on it would result in an error. I didn't know if this is what you intended or not but I added it anyway.
4) Changed another setTimeout to setInterval ( I don't think these change anything, but there's no reason not to use them)

I also saw you were running an asynchronous operation inside of the constructor of the class Webhook. I don't know what your stance on this is, but this is a typically a bad practice. Constructors are typically only suppose to just return the class instance, and any operations that may need to mutate the object should be done outside using a method.

Edit: I also built this and loaded into the game and it seemed to be fine.

### CODE REVIEW

**Comment by Tarnadas** [comment]
Can you squash the last two commits into their respective related commits?
Otherwise I don't see any problem.

About the async self executing function inside the constructor, J don't see any problem. I could instead move it into its own async function, but I would still call it from the constructor, so it wouldn't make a difference

**Comment by UnseenFaith** [comment]
```js
class MyClass {
    constructor() {
        (async () => {
            let result = await foo();
            this.someProperty = result;
            console.log(this.someProperty);// outputs: bar
        })();
    }
}

function foo() {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve('bar'), 2000);
    });
}

new MyClass();
```

Here's some example code on why async constructors don't really work. The class is created without the property there, which then gets added 2 seconds later to the class. The moment you try to access any of the properties created in that async function before the request has actually been fulfilled, it will throw an error.

Typically, the more correct way of doing something like this is:
```js
class MyClass {
    constructor() {
        this.someProperty = null;
    }
  someAsyncMethod() {
    this.someProperty = await foo();
  }
}

function foo() {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve('bar'), 2000);
    });
}

const c = new MyClass();
(await c.someAsyncMethod).someProperty // bar, when ran in an async function
```

**Comment by UnseenFaith** [comment]
Alright, I think I squashed them correctly.

**Comment by UnseenFaith** [comment]
You were doing
```js
this.loops.bind(this);
``` 
This doesn't do anything beside bind the new function and leave it to nothing. That's why it's unnecessary. I rebound the context of the function in the actual setInterval call.

I messed up the onChatMessage binds... but if they're being called by Client objects that should instead be declared on the client object, and not the websocket server.

**Comment by UnseenFaith** [comment]
```js
  onChatMessage (msg) {
    // broadcast to all players
    for (const player of players) {
      player.client.ws.send(msg)
    }
  }
```
This is the snippet for onChatMessage. No where in this snippet do you ever refer to the context of which the function is ran in, which makes binding it completely unnecessary.

**Comment by Tarnadas** [comment]
https://github.com/Tarnadas/net64plus-ded/blob/dev-1.x/src/WebSocketServer.js
Sorry this was kind of hidden. I'll merge this into master and therefore the bind is necessary. I also like keeping all my bindings in the constructor.

**Comment by UnseenFaith** [comment]
Yeah, in that case, the bindings are necessary, and I'll add back the bindings to the constructor. I do think it's better, in terms of code quality, to follow a more oop paradigm though.

**Comment by Tarnadas** [comment]
Please squash again the last two commits. 
Also I've just seen, that you are not using JavaScript Standard rules for linting. Unfortunately I haven't set up proper linting in this repository, but you basically just have to remove the semicolons and it should be fine. I will add proper linting rules once I get back to working on the server

**Comment by UnseenFaith** [comment]
Will do. I accidentally added the semi-colons since I'm a big advocate of them. I'll squash them into the same commit as well.

**Pull request merged**
